### ISSUE TITLE
NationalMap data curation 18 Oct 2022

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1192]
- [x] QLD - Local Government Brisbane City Council - get rid of Superseded datasets - @nf-s 
- [x] GA Marine data - services updated - follow up on URLs - to remove until new services are provided http://marine.ga.gov.au/geoserver/marine/wms - Ana; email sent - https://github.com/TerriaJS/nationalmap/issues/1195
- [x] SA - Department of Energy and Mining - gas tenements not working (all others are working) - get in touch with SA Gov - Ana; the WFS in CKAN works when uploaded to NatMap; emailed data.sa https://services.sarig.sa.gov.au/vector/gas_storage_tenements/wfs?service=wfs&version=1.1.0&REQUEST=GetCapabilities
- [x] data.gov.au - ABARES - Catchment Land 2017 group empty - reach out to ABARES - Ana; checked data.gov.au no geo service available; emailed ABARES
![image](https://user-images.githubusercontent.com/18452161/196331937-fe382113-9f03-446e-9e29-8f037400da8a.png)
- [x] NSW Live data - Randwick open data soft broken - get in touch with Randwick City Council - Ana; emailed council. No public live data is available without authentication (TBC) 
- [x] Marine and Oceans - NSW Marine protected areas - broken - fixed by https://github.com/TerriaJS/terriajs/pull/6604 @nf-s 
- [x] Data.gov.au - Department of State Growth (Tasmania) - Tasmania vehicle crush data broken - Ana to reach out. When tested with the WMS available on data.gov.au, it works on NationalMap https://nationalmap.gov.au/#share=s-yKYPQqGavz6NhXgLiLvV33m8OlF. This is the URL: https://data.stategrowth.tas.gov.au/ags/rest/services/PUBLIC/CDM_CRASH/MapServer/0 - @nf-s to confirm if issue still with Tas, data.gov.au or natmap/terriajs. And this is the data page on data.gov.au: https://data.gov.au/dataset/ds-dga-8f7d9792-dde8-4d88-966a-1874c775640f/details?q=tasmanian%20vehicle
![image](https://user-images.githubusercontent.com/18452161/196332950-ca101159-bcd3-4599-ae1d-4b252db4505f.png)
- [x] Tasmanian Government - Census - empty group - Ana to reach out - emailed - https://github.com/TerriaJS/nationalmap/issues/1194
![image](https://user-images.githubusercontent.com/18452161/196333084-52199450-b83a-480a-8b46-beaf48c83d04.png)
- [x] Tasmanian Government - State - Wealth from Water. Connect directly to their ArcGIS REST group - @nf-s 
![image](https://user-images.githubusercontent.com/18452161/196333332-f8a74971-6ffe-4d0f-9044-8d8ec0061fac.png)
- [x] QLD - Local gov - Sunshine Coast - reach out to get the Esri Portal connected https://data.sunshinecoast.qld.gov.au/ - Ana; https://github.com/TerriaJS/nationalmap/issues/1198
- [x] data.gov.au - ATO - duplicate the Taxation statistics and replace the manually created group under Social and Economic section - https://nationalmap.gov.au/#share=s-4Hyyn6tJCEIFbTGrGpTl1CJ8dLl  - @nf-s

**Comment by nf-s** [comment]
Will be done when these are merged

- [ ] https://github.com/TerriaJS/saas-catalogs-public/pull/268
- [ ] https://github.com/TerriaJS/saas-catalogs-public/pull/269
