### ISSUE TITLE
Add new Local Governments to NationalMap-Catalog (ongoing task)

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/nationalmap#396]
Here is an ongoing task list to document the inclusion of Local Governments correctly into the NationalMap Catalog (https://github.com/TerriaJS/NationalMap-Catalog/blob/master/datasources/includes/Local_Government.ejs)

- [x] Frankston (http://data.gov.au/organization/frankston-city-council) - added in TerriaJS/NationalMap-Catalog#32
- [x] Central Goldfields Shire Council (http://data.gov.au/organization/central-goldfields-shire-council) - added in TerriaJS/NationalMap-Catalog#32
- [x] City of Whittlesea (http://data.gov.au/organization/city-of-whittlesea) - added in TerriaJS/NationalMap-Catalog#32
- [x] Yarra Ranges Council (http://data.gov.au/organization/edit/yarra-ranges-council) - added in TerriaJS/NationalMap-Catalog#32 (note #388 needs to fix lga-filter)
- [x] Cairns Regional Council (http://data.gov.au/organization/cairns-regional-council) (note #388 needs to fix lga-filter)
- [x] City of Boroondara (http://data.gov.au/organization/city-of-boroondara)
- [x] City of Mitcham (http://data.sa.gov.au/data/organization/city-of-mitcham)
- [x] City of Prospect (http://data.sa.gov.au/data/organization/city-of-prospect)
- [x] Moreton Bay Regional Council (http://data.moretonbay.qld.gov.au/)
- [x] Rockhampton Regional Council (http://localdata.net.au/organization/rockhampton-regional-council)

Currently no datasets

- [x] Lake Macquarie City Council (http://data.gov.au/organization/lake-macquarie-city-council)
- [x] Greater Shepparton City Council (http://data.gov.au/organization/greater-shepparton-city-council)
- [x] Moyne Shire Council (http://data.gov.au/organization/moyne-shire-council)
- [x] Warrnambool City Council (http://data.gov.au/organization/warrnambool-city-council)
- [x] City of Palmerson (http://data.gov.au/organization/city-of-palmerston)
- [x] City of Tea Tree Gully (http://data.sa.gov.au/data/organization/city-of-tea-tree-gully)
- [x] Mount Barker District Council (http://data.sa.gov.au/data/organization/mount-barker-district-council)
- [x] Naracoorte Lucindale Council (http://data.sa.gov.au/data/organization/naracoorte-lucindale-council)

**Comment by keithmoss** [comment]
Western Australia has an additional three LGAs with data published now:

- [ ] City of Joondalup (http://catalogue.beta.data.wa.gov.au/organization/city-of-joondalup)
- [ ] City of Perth (http://catalogue.beta.data.wa.gov.au/organization/city-of-perth)
- [ ] City of Wanneroo (http://catalogue.beta.data.wa.gov.au/organization/city-of-wanneroo)

The existing City of Swan entry appears to be a bit bugged as well - it should be showing the one dataset they have at http://catalogue.beta.data.wa.gov.au/organization/city-of-swan, but it shows some of our groups instead:

![screen shot 2017-01-09 at 10 17 11](https://cloud.githubusercontent.com/assets/5944358/21755881/d1013440-d654-11e6-8244-eb9a16635361.png)

**Comment by tobybellwood** [comment]
I've had a look into this - Joondalup, Perth and Wanneroo were disabled (because they required auth to list datasets).  The grouping appears because the Group is set for those datasets in CKAN.
