### ISSUE TITLE
Notify data custodians of issues with services

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#676]
- [x] VIC Gov - Bioregional conservation status - endangered (https://github.com/TerriaJS/nationalmap/issues/674#event-1434501256) 

- [x] VIC Gov - Seismic survey lines https://github.com/TerriaJS/nationalmap/issues/670 

- [x] SA Gov - Adelaide metro - https://github.com/TerriaJS/nationalmap/issues/650

- [x] CSIRO Oceans and atmosphere – Hobart -> IMOS SOOP Sea Surface Temperature Data collected on the Merchant Vessel Sea Flyte (Rottnest Island Ferry) (https://github.com/TerriaJS/nationalmap/issues/670)

- [x] BoM hydrology catchments - https://github.com/TerriaJS/nationalmap/issues/649 

- [x] Local Gov - Ballarat - Ballarat 1 m contours (only the GeoJSON not working; from data.gov.au https://data.gov.au/dataset/ballarat-1m-contours)

- [x] Dept of Communications - Communications - Telecommunications in New Developments

**Comment by AnaBelgun** [comment]
Followed up with all the above and copied Data.gov.au team when necessary.
