### ISSUE TITLE
NatMap - May 2019 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#854]
- [x] satellite imagery layers naming and organisation overhaul: https://github.com/TerriaJS/nationalmap/issues/852 - closed; replaced with #860 

- [x] Satellite imagery layers renamed as of 24 May: https://github.com/TerriaJS/nationalmap/issues/860

- [x] remove Data Providers: https://github.com/terriajs/nationalmap/issues/837 (after #852) 

- [x] reinstate broadband: https://github.com/TerriaJS/nationalmap/issues/859

**Comment by AnaBelgun** [comment]
done by Emma & Kevin
