### ISSUE TITLE
NationalMap - July 2019 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#885]
- [x] WA Dept of Planning: #866 - notified Dept to include the data in their data.wa.gov.au CKAN instance

- [x] add post locations: https://github.com/TerriaJS/nationalmap/issues/878

- [x] bathymetry has new services: https://github.com/TerriaJS/nationalmap/issues/886

- [x] Remote Areas: https://github.com/TerriaJS/nationalmap/issues/888

- [x] Remove broadband data layers - https://github.com/TerriaJS/nationalmap/issues/893

- [x] update to latest TerriaJS

- [x] update to latest terria server 3.0.1 which fixes bug with shortening url when sharing https://github.com/TerriaJS/terriajs/issues/3510

- [x] enable feature time property for blended sat imagery: https://github.com/TerriaJS/NationalMap-Catalog/pull/132

- [x] add anniversary popup: https://github.com/terriajs/nationalmap/issues/884

- [x] fix anniversary popup: https://github.com/TerriaJS/nationalmap/pull/895

**Comment by AnaBelgun** [comment]
done by Nanda.
