### ISSUE TITLE
NationalMap - Oct 19 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#902]
- [x] PR from DTA on Tas datasets: https://github.com/TerriaJS/NationalMap-Catalog/pull/136

- [x] remove ABS group: https://github.com/TerriaJS/nationalmap/issues/900

- [x] add MODIS: https://github.com/TerriaJS/nationalmap/issues/899

- [x] add CDP regions: https://github.com/TerriaJS/nationalmap/issues/890 

- [x] LGAs 2016 under National Boundaries group: https://github.com/TerriaJS/nationalmap/issues/903

- [x] add CLUM 2018: https://github.com/TerriaJS/nationalmap/issues/906

- [x] change limits on requests: https://github.com/TerriaJS/nationalmap/issues/910

- [x] update to latest master (include charts) 

- [x] water regulations - reference stations - https://github.com/TerriaJS/nationalmap/issues/918

- [x] remove pop up

**Comment by juan-guerschman** [comment]
if not too late, you may also want to add ABARES' Forests of Australia 2018? 
http://www.asris.csiro.au/arcgis/rest/services/abares/forests_of_australia_2018/MapServer/0 

the one currently in NAt Map doesn't work
https://data.gov.au/geoserver/forests-of-australia-2018/wms
