### ISSUE TITLE
NationalMap - Nov 2019 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#933]
- [x] update blended satellite imagery service (GSKY) - https://github.com/terriajs/nationalmap/issues/927

- [x] add barest Earth 30 years - https://github.com/TerriaJS/nationalmap/issues/934

- [x] update Forests - https://github.com/TerriaJS/nationalmap/issues/919

- [x] GA Sentinel hotspots: https://github.com/TerriaJS/nationalmap/issues/935

- [x] update charting (catalogue of sat imagery) to show dots instead of lines: https://github.com/TerriaJS/nationalmap/issues/936

**Comment by soyarsauce** [comment]
- [ ] update to terriajs 7.10.0

**Comment by soyarsauce** [comment]
Staging available @ http://staging.nm.terria.io/

**Comment by soyarsauce** [comment]
Released to staging, GA have put onto preprod - ball is in their court.(?)

**Comment by AnaBelgun** [comment]
released on 6 Dec 2019
