### ISSUE TITLE
NationalMap - Migration to v8 Sep 20-Feb 21

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#968]
Checklist 

**Dec 2020 release items:**  - done

- [x] About Pages : https://docs.google.com/document/d/1FBL0vUtxF5_l-dBAUBtJYys6vA5XwcCM0_Ijf2xrFFs/edit# 
- [x] Welcome modal video: https://youtu.be/C4-gLv09Rfo / <iframe width="560" height="315" src="https://www.youtube.com/embed/C4-gLv09Rfo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- [x] WFS

- [x] WMS

- [x] SDMX JSON - https://github.com/TerriaJS/terriajs/issues/3524

- [x] CSV

- [x] terrace to be synced to upstream TerriaMap https://github.com/TerriaJS/terrace/issues/151

----------------------------------------------------------------------------------------------------------------------------------------------

**Post Dec 2020 release:** 
- [ ] NationalMap catalogue https://github.com/TerriaJS/nationalmap/issues/985 - needs SDMX fixes and https://github.com/TerriaJS/terriajs/pull/5085 merged

- [ ] CKAN support for data.gov.au - https://github.com/terriajs/nationalmap/issues/987 (show data with no filter) 
- [ ] MAGDA API support for data.gov.au - search?

- [ ] MAGDA integration _ https://github.com/TerriaJS/nationalmap/issues/981 and https://github.com/TerriaJS/TerriaMap/issues/489 

- [ ] GeoJSON

- [ ] KML/KMZ

- [ ] Boundaries: e.g. http://geoserver.nationalmap.nicta.com.au/admin_bnds_abs/ows 

- [ ] region mapping

- [ ] vector tiles

- [ ] csw https://github.com/TerriaJS/terriajs/issues/4693

- [x] YourDataYourRegions https://github.com/TerriaJS/terriajs/issues/4861

**Comment by AnaBelgun** [comment]
as discussed in Planning, we'll do v1 sometime in Aug and start testing to discover gaps in support

**Comment by soyarsauce** [comment]
A development instance of this is now up at http://nationalmap.saas.terria.io/

**Comment by AnaBelgun** [comment]
Useful comments in here: https://github.com/TerriaJS/catalog-converter/pull/11#pullrequestreview-509122965

**Comment by mwu2018** [comment]
> A development instance of this is now up at http://nationalmap.saas.terria.io/
> It takes the live v7 production nationalmap catalog and turns it into a v8 mobx-friendly catalog, some datasets will be empty because they contain datasets that are either not yet supported in mobx or the catalog-converter

@soyarsauce This link is broken: http://nationalmap.saas.terria.io/

**Comment by soyarsauce** [comment]
Re: catalog https://nationalmap.dev.saas.terria.io/ used to have the catalog, but it's since lost that capability from a bug in terriajs. Emma says she's releasing new terriajs+terrace today so that should come back to life when that happens!

**Comment by soyarsauce** [comment]
(to be clear, right now it simply points to the production v7 NM catalog as seen in https://dev.saas.terria.io/api/v0/registry/records/map-config-nationalmap?aspect=terria-saas , and translates that to v8 catalog on the fly)

![image.png](https://images.zenhubusercontent.com/5ca14bcde8443113da47c346/1a5d6412-582f-4343-a127-4faf4bf314ea)

**Comment by nf-s** [comment]
- [ ] change to manual v8 catalog (not on the fly)
- [ ] create catalog-converter issue with missing types, properties...

**Comment by AnaBelgun** [comment]
SDMX .stats integration TODO: 


- [ ] Currently I'm only seeing the top level of our categories (PEOPLE, LABOUR, etc.) there should be at least two levels below that. 

- [ ] The catalogue has "ABS -> Australian Bureau of Statistics -> ABS Topics"  it would be good to remove one or two of those levels so people can find data with fewer clicks.

**Comment by steve9164** [comment]
Icons & image on saas.terria.io versions of nationalmap point to nationalmap.gov.au. When we switch over that domain all of those image will be blank if we don't fix those images first.

Also need to get the about pages nationalmap logo from nationalmap.gov.au and host that in storage to set a brandingImageUrl for new about pages.

**Comment by AnaBelgun** [comment]
To avoid further confusion about releases, we'll integrate the migration to V8 into normal / monthly release cycle of apps; hence the release tickets will be merged with migration ones

**Comment by AnaBelgun** [comment]
Items in this ticket are now incorporated in Jan release ticket https://github.com/TerriaJS/nationalmap/issues/982
