### ISSUE TITLE
NationalMap - Aug 2020 release (on master) 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#969]
Final release on master to solve some urgent data issues (i.e. NBN cache causing issues with legends)

- [x] https://github.com/TerriaJS/nationalmap/issues/967 - dependent on https://github.com/TerriaJS/nationalmap/issues/166  - resolved by https://github.com/TerriaJS/NationalMap-Catalog/pull/166

- [x] https://github.com/TerriaJS/nationalmap/issues/966#issuecomment-667006078

- [x] Base map update: https://github.com/TerriaJS/nationalmap/issues/965 - done here https://github.com/TerriaJS/terriajs/pull/4624

- [x] Population density update: https://github.com/TerriaJS/nationalmap/issues/964 - resolved by https://github.com/TerriaJS/NationalMap-Catalog/pull/166

- [x] health data covid - https://github.com/TerriaJS/nationalmap/issues/973 

- [x] welcome modal - https://github.com/TerriaJS/nationalmap/issues/971

**Comment by AnaBelgun** [comment]
@reginapramesti a couple of questions: 

1) testing the legends problem / automatic update after changing in data.gov.au if resolved by not going through proxy, can be done when in pre-prod at GA? or only after is actually published 
2) when testing the population density it errors out: 
![image](https://user-images.githubusercontent.com/18452161/91251874-af97d100-e79f-11ea-825b-ad01cdaa41ee.png)

If you test by adding the service url to the map, it works: 
https://services.ga.gov.au/gis/services/NEXIS_Residential_Dwelling_Density/MapServer/WMSServer

http://staging.nm.terria.io/#share=s-n3IiF8oqjKpvnE1aWXyfoRcoGce

![Uploading image.png…]()

**Comment by AnaBelgun** [comment]
- @rowanwins @reginapramesti I think we need to double check the population layer to make sure the version published is not different from the updated service; below is a share url with both versions (nexis service url as Add my data and the one we included in the catalogue for  this version of NationalMap without the legend); no need to fix the legend issue in v7 just to make sure the version we publish is correct; to test click on a dark coloured spot with both layers turned on; the values seem different 

https://preprod.nationalmap.gov.au/#share=s-117qMwpopnDnISd4WEjeNgYbO4n

**Comment by reginapramesti** [comment]
I see the problem! Looks like it's because there's a layer 0 as part of the Esri MapServer service, and we forgot to modify the layers we're including so it was showing `"layers": "1,2,3,4,5"` and not layer 0 (which is the most fine-grained one, 100m). So essentially the values are different because we are comparing the 100m value (from the service) against the 500m value (from the catalogue).

Anyway now I've removed the part where we specify which layers we're using because I assume we want all of the layers from this service

**Comment by rowanwins** [comment]
Ah this is another frustrating with how this layer is published and how Terria then makes requests on click

**Comment by AnaBelgun** [comment]
@reginapramesti thank you for re-releasing NationalMap on staging; @AnaBelgun to reach out to Scott
