### ISSUE TITLE
NationalMap - Jan 2021 release (v8)

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#982]
**HIGH PRIORITY:** 
- [ ] AREMI catalogue transfer to NatMap https://github.com/TerriaJS/aremi-natmap/issues/437  - Data transfer mapping is [HERE ](https://csiroau.sharepoint.com/:w:/r/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/AREMI/Data/Decommissioning%20-%20data%20transfer%20to%20NatMap/AREMI%20data%20transfer%20to%20NatMap%20-%20mapping%20to%20catalogue.docx?d=w807583b6b8684cfa85cbc4fefa064729&csf=1&web=1&e=DqTrGg)
V8 porting related issues for AREMI data: 
- Token implementation for WA services: https://github.com/TerriaJS/aremi-natmap/issues/437
- ISF data - investigate CSS custom sheets and vector data handling: https://github.com/TerriaJS/aremi-natmap/issues/439 
- Traffic volumes - NSW transport API - https://github.com/TerriaJS/aremi-natmap/issues/440
- AEMO data - csv polling - feature info disappears after 1 cycle / polling - insert ticket https://github.com/terriajs/terriajs/issues/4768 

**MEDIUM PRIORITY:**

- [ ] Help page (under About) needs to be deleted
- [ ] update some GA layers: https://github.com/TerriaJS/nationalmap/issues/986
- [ ] NationalMap catalogue https://github.com/TerriaJS/nationalmap/issues/985 - needs SDMX fixes and https://github.com/TerriaJS/terriajs/pull/5085 merged
- [ ] YourDataYourRegions https://github.com/TerriaJS/terriajs/issues/4861
- [ ] CKAN support for data.gov.au - https://github.com/terriajs/nationalmap/issues/987 (show data with no filter) 
- [ ] MAGDA API support for data.gov.au - search?
- [ ] MAGDA integration _ https://github.com/TerriaJS/nationalmap/issues/981 and https://github.com/TerriaJS/TerriaMap/issues/489 
- [ ] GeoJSON
- [ ] KML/KMZ
- [ ] Boundaries: e.g. http://geoserver.nationalmap.nicta.com.au/admin_bnds_abs/ows 
- [ ] region mapping
- [ ] vector tiles
- [ ] csw https://github.com/TerriaJS/terriajs/issues/4693

**LOW PRIORITY**

- [ ] NSW decimal issue: https://github.com/TerriaJS/nationalmap/issues/980 
- [ ] Update Mobile black spot data position in catalogue - https://github.com/TerriaJS/nationalmap/issues/979

**Comment by AnaBelgun** [comment]
January release with AREMI Data done on 1 Feb 2021
rest of the tickets - included in NationalMap Feb 2021 release
