### ISSUE TITLE
NationalMap - February 2021 v8 release 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#992]
Release NationalMap on v8 (ideally end of February 2021): 

- [ ] release stand alone NationalMap v8 

- [ ] Help page (under About) needs to be deleted

- [ ] update some GA layers: #986

- [ ] NationalMap catalogue #985 - needs SDMX fixes and TerriaJS/terriajs#5085 merged

- [ ] YourDataYourRegions TerriaJS/terriajs#4861

- [ ]  CKAN support for data.gov.au - #987 (show data with no filter)

- [ ] MAGDA API support for data.gov.au - search?

- [ ]  MAGDA integration _ #981 and TerriaJS/TerriaMap#489

- [ ]  GeoJSON

- [ ] KML/KMZ

- [ ] Boundaries: e.g. http://geoserver.nationalmap.nicta.com.au/admin_bnds_abs/ows

- [ ] region mapping

- [ ]  vector tiles

- [ ] csw TerriaJS/terriajs#4693

LOW PRIORITY

- [ ] NSW decimal issue: #980

- [ ] Update Mobile black spot data position in catalogue - #979

**Comment by AnaBelgun** [comment]
Superseeded by #997
