### ISSUE TITLE
NationalMap - Beta release (V8) - Feb 2021

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#997]
This epic is to keep track of all the tickets related to AREMI data migration and NationalMap release on v8 and decommissioning of v7. It will supersede: 
- AREMI migration to NationalMap https://github.com/TerriaJS/aremi-natmap/issues/437
- NationalMap Feb 2021 v8 release

**Comment by AnaBelgun** [comment]
Breakdown: 

**High priority:** 

- [ ] NationalMap v8 - standalone map (un-SaaS) https://github.com/TerriaJS/nationalmap/issues/990 
- [ ] SDMX - Go through ABS SDMX dataflows - make sure region mapping is working as expected - make sure default values are sensible 
- [ ] AREMI - ISF - Add Network opportunities - https://github.com/TerriaJS/aremi-natmap/issues/439 
- [ ] AREMI - Wave Atlas 
- [ ] <ins>csw: 1 &mdash; **We don't support CSW in v8** https://github.com/TerriaJS/terriajs/issues/4693</ins>
- [ ] <ins>wps-getCapabilities: **We don't support WPS-group in v8** https://github.com/TerriaJS/terriajs/issues/5150</ins>
  - [ ] itemProperties
    - [ ] cacheDuration
    - [ ] contextItem
      - [ ] name
      - [ ] description
      - [ ] layers
      - [ ] url
      - [ ] type
      - [ ] legendUrls
      - [ ] rectangle
      - [ ] ignoreUnknownTileErrors


Medium priority: 

- [ ] AREMI -  Generation -> Small Scale Installations - color binning not quite the same - MEDIUM

**Comment by nf-s** [comment]
#### Legend issues

- [ ] <ins>Make sure legend URLs are all PROXIED</ins>
  - [ ] Test styles `LegendURL`
  - [ ] Test custom legend in catalog JSON

**Comment by nf-s** [comment]
## Unknown types: 
  - wfs-getCapabilities: 1
  - socrata: 1
  - sdmx-json: 346

## Unknown properties: 
- EsriMapServerCatalogItem: 
  - dataUrl: 10
  - dataUrlType: 11
  - getFeatureInfoFormats: 1

- CsvCatalogItem: 
  - charSet: 2
  - dataUrlType: 1
  - dataUrl: 1

- WebMapServiceCatalogItem: 
  - dataUrl: 32
  - dataUrlType: 32
  - useOwnClock: 46

- WebMapServiceCatalogGroup: 
  - dataUrl: 1
  - dataUrlType: 1
  - blacklist: 16

- MapboxVectorTileCatalogItem: 
  - dataUrl: 3
  - dataUrlType: 1

- CatalogGroup: 
  - preserveOrder: 12
  - custodian: 1
  - initialMessage: 1

- SensorObservationServiceCatalogItem: 
  - tryToLoadObservationData: 2

- CkanCatalogItem: 
  - debugFormat: 165

- CkanCatalogGroup: 
  - blacklist: 2
  - minimumMaxScaleDenominator: 77
  - filterByWmsGetCapabilities: 77
  - includeCsv: 83
  - includeGeoJson: 82
  - includeKml: 83
  - includeWms: 81
  - includeWfs: 80
  - includeEsriMapServer: 80
  - includeEsriFeatureServer: 80
  - allowEntireWmsServers: 1
  - csvResourceFormat: 1
  - useResourceName: 1

- EsriMapServerGroup: 
  - itemProperties: 1

**Comment by nf-s** [comment]
Color binning issues (low priority):

- [ ] Add support for ColorBrewer strings - eg "8-class Reds" https://github.com/TerriaJS/terriajs/issues/5215

**Comment by nf-s** [comment]
- [ ] Discuss with team to add `proxyAuth` for NSW traffic / WA slip services + future of data on NSW DT GeoServer

**Comment by nf-s** [comment]
## Feb release checklist

- [ ] Push new catalog from dev to prod
- [ ] Discuss with team to add `proxyAuth` for NSW traffic / WA slip services + future of data on NSW DT GeoServer

**Comment by nf-s** [comment]
## Feb 28 Release

https://nationalmap.test.saas.terria.io/

**Awaiting terriajs version update**

### New datasets

- Agriculture/Agricultural Exposure
- Maritime boundaries
    - Australian Maritime Boundary Treaties AMB2014a
    - Australian Shoreline
    - CWTH CW Act 1980 Coastal Waters
- Boundaries/Other areas
    - CWTH OMA 1994 Mineral Blocks AMB2014a
    - CWTH OPGGSA 2006 AMB2014a
    - CWTH OPGGSA 2006 Petroleum Blocks AMB2001a
    - CWTH OPGGSA 2006 Petroleum Blocks AMB2014a
    - SSLA 1973 AMB2014a
- Bathymetry/Geoscience Australia Marine Data (WFS)
- Water/Surface Water/Individual Hydrology and Marine Layers/Surface Hydrology

### Updated

- Network Opportunities/New Generator Connection Capacity/Distribution/Distribution powerlines
- Network Opportunities/New Generator Connection Capacity/Distribution
- Network Opportunities/New Generator Connection Capacity/Transmission/Transmission powerlines
- Network Opportunities/New Generator Connection Capacity/Transmission/Transmission substations
- Network Opportunities/Supporting Information/Distribution boundaries
- Network Opportunities/Supporting Information/Transmission Lines

**Comment by AnaBelgun** [comment]
@nf-s testing Feb 21 release: 
- when adding data such as the Bathymetry, click ideal zoom and try to zoom in, the app crashes (white screen)
- the rest seems fine

**Comment by nf-s** [comment]
Some of those Bathymetry WFS datasets are large - which can hang or crash Terria.  
We can either disable the large datasets, or try to progress https://github.com/TerriaJS/terriajs/issues/4633 (Client-side vector support)

**Comment by AnaBelgun** [comment]
ok, let's leave them for now in the release. The reason is that we have more than a couple, and if we disable one, two, we should do it for all. We definitely need to progress the client side vector support. We can start in March.

**Comment by AnaBelgun** [comment]
just to clarify @nf-s: let's release in Beta.

**Comment by nf-s** [comment]
NationalMap beta is now updated - https://beta.nationalmap.terria.io/

**Comment by nf-s** [comment]
- [ ] CSW is done - so add Marine energy context CSW
- [ ] Merge SDMX 2

**Comment by AnaBelgun** [comment]
@nf-s once dev/test is pushed, please move the SDMX and Wave into May 2021 list; thank you

**Comment by nf-s** [comment]
@AnaBelgun I think we can do all Software migration issues by end of Aug except for "Fixed pickedFeatures for dynamic layers" - which may require more time

**Comment by AnaBelgun** [comment]
@nf-s that's great; now that we have v8 out of the way, we can start

**Comment by nf-s** [comment]
## nf-s' wish list

- Use new mvt to fix WFS/OpenDataSoft/Socrata/GeoJSON performance
  - Leave region mapping as is for the moment
- Error message quick scan
- disambigDataReplacement doesn't exits in v8 terriajs#5213 - high (prevents some of the data to be available; e.g. Energy - Renewables - WA - Cereal Straw [https://github.com/TerriaJS/terriajs/issues/5213](https://github.com/TerriaJS/terriajs/issues/5213)
- CKAN cleanup (adding formats)
    - Remove CKAN groups which have no datasets
- Data.gov.au?
- Think about search
    - Maybe catalog-indexer tool - which loads all dynamic groups and shoves model ids/names into JSON file which is loaded into terriajs
- Add NBN layers to Comms group (cripsy = truly high priority)

**Comment by t83714** [comment]
Created a staging site for data.gov.au here: https://staging.search.data.gov.au/ and upgraded to v60

See ticket here: https://github.com/magda-io/magda-config-data.gov.au/issues/35

Seems "Open in NationalMap" button doesn't work with https://nationalmap-2021-09-03.nm.terria.io/
nor https://beta.nationalmap.terria.io/
However, it works with other v8 map e.g. https://nsw.digitaltwin.terria.io/

**Comment by t83714** [comment]
Probably an easier to test example to debug the issue above (you don't need Magda frontend to reproduce the issue).
So digital twin work with this link:
https://nsw.digitaltwin.terria.io/#start=%7B%22initSources%22%3A%5B%7B%22catalog%22%3A%5B%7B%22name%22%3A%22Manningham%20Street%20Trees%20-%20Preview%20this%20Dataset%20(WMS)%22%2C%22type%22%3A%22magda%22%2C%22recordId%22%3A%22dist-dga-125506f6-5954-43e5-9529-67a9c170a72e%22%2C%22url%22%3A%22https%3A%2F%2Fdev.magda.io%2F%22%2C%22id%22%3A%22data.gov.au-postMessage-dist-dga-125506f6-5954-43e5-9529-67a9c170a72e%22%7D%5D%2C%22workbench%22%3A%5B%22data.gov.au-postMessage-dist-dga-125506f6-5954-43e5-9529-67a9c170a72e%22%5D%7D%5D%7D

But national map doesn't work:
https://nationalmap-2021-09-03.nm.terria.io/#start=%7B%22initSources%22%3A%5B%7B%22catalog%22%3A%5B%7B%22name%22%3A%22Manningham%20Street%20Trees%20-%20Preview%20this%20Dataset%20(WMS)%22%2C%22type%22%3A%22magda%22%2C%22recordId%22%3A%22dist-dga-125506f6-5954-43e5-9529-67a9c170a72e%22%2C%22url%22%3A%22http%3A%2F%2Flocalhost%3A6108%2F%22%2C%22id%22%3A%22data.gov.au-postMessage-dist-dga-125506f6-5954-43e5-9529-67a9c170a72e%22%7D%5D%2C%22workbench%22%3A%5B%22data.gov.au-postMessage-dist-dga-125506f6-5954-43e5-9529-67a9c170a72e%22%5D%7D%5D%7D

In the real code Magda send the catalog item via postMessage:
https://docs.terria.io/guide/deploying/controlling-in-an-iframe-or-popup/

But the data is same as what we sent via `#start` urls above.
